name: E2E on Chrome

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          project: ./site
          browser: chrome
          build: npm install
          start: npm run dev
          wait-on: "http://localhost:5173"
